name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          # GitHub Actions environment
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            sudo apt-get update
            sudo apt-get install -y imagemagick libmagickwand-dev
            
            # Configure ImageMagick to allow PDF and other formats
            sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml || true
            sudo sed -i 's/rights="none" pattern="XPS"/rights="read|write" pattern="XPS"/' /etc/ImageMagick-6/policy.xml || true
            
            # Install additional image codecs
            sudo apt-get install -y libjpeg-dev libpng-dev libtiff-dev libwebp-dev
            
            # Install ICC color profiles
            sudo apt-get install -y icc-profiles icc-profiles-free
            
            # Create directory for ICC profiles if it doesn't exist
            sudo mkdir -p /usr/share/color/icc/profiles
            
            # Download common ICC profiles if not available
            if [ ! -f "/usr/share/color/icc/sRGB.icc" ]; then
              sudo wget -q -O /usr/share/color/icc/sRGB.icc https://www.color.org/srgbprofiles.xalter || true
            fi
            
            # List available ICC profiles for debugging
            echo "Available ICC profiles:"
            find /usr/share/color -name "*.icc" 2>/dev/null || echo "No ICC profiles found"
            
            # Verify ImageMagick installation
            magick -version || convert -version
          else
            # Local wrkflw environment - skip system dependencies
            echo "Running in local environment, skipping system dependency installation"
          fi

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          # Check if we're in local wrkflw environment
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            # Install additional test dependencies
            pip install pytest-xvfb  # For headless GUI testing if needed
          else
            # Local environment - basic installation only
            echo "Local environment detected - installing minimal dependencies"
            which pip && pip install pytest || echo "pip not available, continuing"
          fi

      - name: Verify environment setup
        run: |
          echo "=== Environment Check ==="
          echo "Python version: $(python --version 2>&1 || echo 'Python not available')"
          echo "Pip version: $(pip --version 2>&1 || echo 'Pip not available')"
          echo "Working directory: $(pwd)"
          echo "Environment variables:"
          echo "  GITHUB_ACTIONS: ${GITHUB_ACTIONS:-not set}"
          echo "  HOME: ${HOME:-not set}"
          echo "Directory contents:"
          ls -la || echo "ls command failed"

          # Optional dependency checks (non-failing)
          python -c "import PIL; print(f'Pillow version: {PIL.__version__}')" 2>/dev/null || echo "Pillow not available"
          python -c "import cv2; print(f'OpenCV version: {cv2.__version__}')" 2>/dev/null || echo "OpenCV not available"
          python -c "import numpy; print(f'NumPy version: {numpy.__version__}')" 2>/dev/null || echo "NumPy not available"
          python -c "import piexif; print('piexif imported successfully')" 2>/dev/null || echo "piexif not available"
          python -c "import noise; print('noise imported successfully')" 2>/dev/null || echo "noise not available"

          # Test ImageMagick availability (optional in local environment)
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            python -c "import subprocess; subprocess.run(['magick', '-version'], check=True)" || \
            python -c "import subprocess; subprocess.run(['convert', '-version'], check=True)"
          else
            echo "Skipping ImageMagick test in local environment"
          fi

      - name: Run basic Python tests
        run: |
          echo "=== Basic Python Tests ==="
          python -c "print('Python environment is working')" || exit 1

          # Test if main module can be imported
          python -c "import sys; sys.path.insert(0, 'src'); print('Source directory accessible')" || echo "Source import test failed (non-critical)"

          # Check if main CLI exists
          if [ -f "toolkit.py" ]; then
            echo "Main CLI script found"
            python -c "import ast; ast.parse(open('toolkit.py').read()); print('CLI script syntax OK')" || echo "CLI syntax check failed (non-critical)"
          else
            echo "Main CLI script not found"
          fi

          echo "Basic Python tests completed successfully"

      - name: Run original image generation tests
        run: |
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            pytest tests/test_original_generation.py -v --tb=short
          else
            echo "Skipping image generation tests in local environment (requires ImageMagick)"
          fi

      - name: Run variation generation and validation tests
        run: |
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            pytest tests/test_variation_generation.py -v --tb=short
          else
            echo "Skipping variation tests in local environment (requires ImageMagick)"
          fi

      - name: Test CLI commands (integration test)
        run: |
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            # Test generate-original command
            python toolkit.py generate-original --output-dir test_output --test-compliance
            
            # Test generate-variations command  
            python toolkit.py generate-variations --source-dir test_output --output-dir test_output
            
            # Verify output files exist
            ls -la test_output/
            ls -la test_output/jpeg/ | head -10
            ls -la test_output/png/ | head -10
            ls -la test_output/gif/ | head -10
            
            # Verify index.json was created
            test -f test_output/index.json
            wc -l test_output/index.json
          else
            # Basic CLI test for local environment
            echo "=== Basic CLI Test ==="
            if [ -f "toolkit.py" ]; then
              echo "toolkit.py found, testing basic functionality"
              python toolkit.py --help 2>&1 || echo "CLI help test completed (may have failed but non-critical)"
            else
              echo "toolkit.py not found in current directory"
            fi
            echo "CLI test completed"
          fi

      - name: Final success confirmation
        run: |
          echo "=== Workflow Completion ==="
          if [ "$GITHUB_ACTIONS" = "true" ]; then
            echo "GitHub Actions environment: All tests completed"
          else
            echo "Local wrkflw environment: Basic validation completed successfully"
          fi
          echo "Workflow finished successfully"

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        if: always() && env.GITHUB_ACTIONS == 'true'
        with:
          name: test-images
          path: |
            test_output/
            !test_output/jpeg/
            !test_output/png/
            !test_output/gif/
          retention-days: 7

      - name: Archive coverage reports
        uses: actions/upload-artifact@v4
        if: always() && env.GITHUB_ACTIONS == 'true'
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
          retention-days: 7
